### ISSUE TITLE
多平台编译问题

### ISSUE THREAD

**Issue by Droid-MAX** [981213/spi-nand-prog#4]
https://github.com/Droid-MAX/spi-nand-prog

这是我fork之后将CMake编译脚本解构，自行编写了Makefile编译脚本以及不同系统的构建脚本

在armv7l嵌入式Linux系统平台上编译前，需要执行如下命令修改代码才可以顺利编译:

```
sed -i "s/ssize_t/ssize/g" spi-nand/core.c spi-mem/spi-mem.c include/spi-mem.h spi-mem/spi-mem-serprog.c
```

在x86_64架构的Linux平台使用MingW将其编译为exe时会报如下错误:

```
spi-nand-prog/spi-mem/ch347/ch347.h:16:10: fatal error: endian.h: No such file or directory
spi-nand-prog/include/linux-types.h:2:10: fatal error: linux/types.h: No such file or directory
```

**Comment by Droid-MAX** [comment]
@hanwckf 大佬知不知道如何适配编译到windows平台上去呢？

**Comment by Droid-MAX** [comment]
复制宿主机系统endian.h头文件到spi-nand-prog项目的include文件夹里，修改linux-types.h头文件里的linux/types.h为sys/types.h，用sed分别替换ssize_t和loff_t，最终还是编译时报错

**Comment by Droid-MAX** [comment]
在64位Kali虚拟机系统中使用MinGW交叉编译的完整编译日志如下:
https://pastebin.com/raw/bkDCRrju

**Comment by hanwckf** [comment]
1. 去掉`linux_types.h`头文件，手动定义u8 u16 u32等数据类型为unsigned char, unsigned short, unsigned int
2. 去掉`endian.h`头文件，实际上不需要它
3. 手动定义ssize_t和loff_t为unsigned long和long long
4. linux-err.h里面的long替换成long long

**Comment by Droid-MAX** [comment]
非常感谢，我晚点给代码做下补全，以后考虑用GitHub Action做自动编译

**Comment by Droid-MAX** [comment]
改的越多，报错越多。。暂时还是先放一放
